fix unused parameter warning in ixgb_dump_regs()
This fixes:
  external/ethtool/ixgb.c:42:40: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  ixgb_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I674e03805dc9a4633d0299d9f4e88bd4ddb61359