fix unused parameter warning in realtek_dump_regs()
This fixes:
  external/ethtool/realtek.c:244:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  realtek_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I62fa7dbb66d5ae545272b41538198787dbbfbe25