fix unused parameter warning in vioc_dump_regs()
This fixes:
  external/ethtool/vioc.c:14:44: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int vioc_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I2b25a5c4d23af281616847ceb75ca8c70dfb44d0