fix unused parameter warning in amd8111e_dump_regs()
This fixes:
  external/ethtool/amd8111e.c:155:48: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int amd8111e_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I885d775f4b56f75b8f5bfa2abefb00af5abd9f95