fix unused parameter warning in altera_tse_dump_regs()
This fixes:
  external/ethtool/tse.c:28:50: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int altera_tse_dump_regs(struct ethtool_drvinfo *info,

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I555f0e3c55bba999aeb64f1e1435744590ea389d