fix unused parameter warning in et131x_dump_regs()
This fixes:
  external/ethtool/et131x.c:5:46: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int et131x_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I4e90a489bdd3a0a04817149b1b6a86e7ef9f106d