fix unused parameter warning in at76c50x_usb_dump_regs()
This fixes:
  external/ethtool/at76c50x-usb.c:16:48: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  at76c50x_usb_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I4ca9edb1b155c63f14268aebf7bdc81bce53b85d