fix unused parameter warning in ixgbe_dump_regs()
This fixes:
  external/ethtool/ixgbe.c:171:41: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  ixgbe_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I745f6b9582bc176eafdce9e292a4bf2a951c0c69