fix unused parameter warning in de2104[01]_dump_regs()
This fixes:
  external/ethtool/de2104x.c:115:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  de21040_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

  external/ethtool/de2104x.c:421:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  de21041_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I154a2a283f83e22180217b9aeec46bd8290a2200