fix unused parameter warning in lan78xx_dump_regs()
This fixes:
  external/ethtool/lan78xx.c:5:47: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int lan78xx_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Ibc67c27248ca623e9ca8534d43c888af3cf9997b