fix unused parameter warning in fjes_dump_regs()
This fixes:
  external/ethtool/fjes.c:5:44: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int fjes_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Id5409c70e26f4e131a8557a9c8f0a0c921dfefde