fix unused parameter warning in e100_dump_regs()
This fixes:
  external/ethtool/e100.c:40:40: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  e100_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Idc6e3bb3fb837555425ddd6cc903e8763a4c71e1