fix unused parameter warning in igb_dump_regs()
This fixes:
  external/ethtool/igb.c:92:39: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  igb_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: If2e175d1b1bd3976d760dc359b52c304e8334f92