fix unused parameter warning in ixgbevf_dump_regs()
This fixes:
  external/ethtool/ixgbevf.c:6:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  ixgbevf_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I6f3233ceb46bc6b96eca673578fa2a6281ea8ad7