fix unused parameter warning in fec_dump_regs()
This fixes:
  external/ethtool/fec.c:197:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int fec_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I5d53deb593d72dcfde95b62f1651dd8f5d6aa3ba