fix unused parameter warning in sfc_dump_regs()
This fixes:
  external/ethtool/sfc.c:3894:39: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  sfc_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Ia255a280742332c44b66bf8f5bb678abc7e3467b