fix unused parameter warning in netsemi_dump_eeprom()
This fixes:
  external/ethtool/natsemi.c:967:45: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  natsemi_dump_eeprom(struct ethtool_drvinfo *info, struct ethtool_eeprom *ee)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I40d66f887d18ac6e69e1f365767a19f580a44f69