fix unused parameter warning in natsemi_dump_regs()
This fixes:
  external/ethtool/natsemi.c:326:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  natsemi_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Ib45adc15c39be9886fdc77ee488aba6b67726096