fix unused parameter warning in smsc911x_dump_regs()
This fixes:
  external/ethtool/smsc911x.c:5:48: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int smsc911x_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I419e8e365481020241303033fcdfaf31aaf4e178