fix unused parameter warnings in do_version() and show_usage()
This fixes:
  external/ethtool/ethtool.c:473:43: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
  static int do_version(struct cmd_context *ctx)

  external/ethtool/ethtool.c:5392:43: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
  static int show_usage(struct cmd_context *ctx)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I0cc52f33bb0e8d7627f5e84bb4e3dfa821d17cc8