fix unused parameter warning in print_simple_table()
This fixes:
  external/ethtool/sfc.c:3811:29: error: unused parameter 'revision' [-Werror,-Wunused-parameter]
  print_simple_table(unsigned revision, const struct efx_nic_reg_table *table,

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I253158a534c295b13e13dd02461952927cf8814c