fix unused parameter warning in ibm_emac_dump_regs()
This fixes:
  external/ethtool/ibm_emac.c:317:48: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int ibm_emac_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I18f305612e48ae76031ae327acf134d1623a8a3d