fix unused parameter warning in vmxnet3_dump_regs()
This fixes:
  external/ethtool/vmxnet3.c:6:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  vmxnet3_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I5494339c8d17e72424651e7056605cd61aa6d4b8