fix unused parameter warning in dump_eeprom()
This fixes:
  external/ethtool/ethtool.c:1271:70: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  static int dump_eeprom(int geeprom_dump_raw, struct ethtool_drvinfo *info,

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I57c65a8d21c6864d4c09f37bb3d408348ea03c4f