fix unused parameter warning in fec_8xx_dump_regs()
This fixes:
  external/ethtool/fec_8xx.c:50:47: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int fec_8xx_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Iefd61cf2b89804fab8ca6c845196706684ddd45e