fix unused parameter warning in e1000_get_mac_type()
This fixes:
  external/ethtool/e1000.c:258:38: error: unused parameter 'revision_id' [-Werror,-Wunused-parameter]
  e1000_get_mac_type(u16 device_id, u8 revision_id)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I2469ef61996fd273cc3a2a6a7af0ae889c81b02b