fix unused parameter warning in dsa_dump_regs()
This fixes:
  external/ethtool/dsa.c:677:43: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int dsa_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I7da1206aab480823b6aee2aa013db3e2912c8294