fix unused parameter warning in e1000_dump_regs()
This fixes:
  external/ethtool/e1000.c:368:41: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  e1000_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Ib0bf9e87137f256adf6e93f90d7f9426ab376a52