fix unused parameter warning in find_option()
This fixes:
  external/ethtool/ethtool.c:5417:28: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
  static int find_option(int argc, char **argp)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I7782cac5f58e217fc6032037a2f248b03573b9d4