fix unused parameter warning in {skge,sky2}_dump_regs()
This fixes:
  external/ethtool/marvell.c:262:44: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int skge_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

  external/ethtool/marvell.c:382:44: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int sky2_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Ic60f9596ac59f15d44ebb80f9438c4978f13b48c